# Unicode Handler: type special characters with e.g. :smile:
# Permission is unknownutilities.unicode
unicodehandler:
   enabled: true

# Wither Arena management
wither-arena:
  enabled: true
  arena-location:
    world: survival
    X: -476
    Y: 234
    Z: 679
  spectator-location:
    world: survival
    X: -477
    Y: 227
    Z: 721
  podium-location:
    world: survival
    X: -477
    Y: 229
    Z: 632
  paste-location:
    world: survival
    X: -477
    Y: 196
    Z: 676
  sql-database:
    enabled: true
    hostname: 127.0.0.1
    port: '3306'
    database: minecraft
    username: root
    password: pass

# /? override
commandoverrider:
   enabled: true
   
# Maintenance mode features
maintenancemode:
# Should these features be enabled in the plugin? so this ISN'T if maintenance mode is enabled but if the feature in the plugin is enabled
# If this is set to 'true', then you can use maintenance mode.
   enabled: true
   
# NetherTop: Prevents players from building on top of the Nether
nethertop:
   enabled: true

# PlainMessages: Send plain messages using /ubr and /umsg (color codes supported)
plainmessages:
   enabled: true
   
# PrefixChanger: Change your LVL prefix with the /prefix command
prefixchanger:
   enabled: true

# SafeLogin: Protects players from dying if they join (e.g. by falling or lava or suffocation)
safelogin:
   enabled: true

# The command scheduler
scheduledcommandexecutor:
   enabled: true
   # What commands should be executed every time? You can put more or less commands by adding - blabla
   commands:
   - broadcast Don't forget to vote!
   
   # At which intervals (in ticks!) should these commands be executed?
   # 12000 ticks is 10 min. if running 20 ticks per second
   interval: 12000
   
   midnight-commands-enabled: true
   5minbeforemidnight-commands:
   - broadcast The daily restart is coming up in 5 minutes! 
   1minbeforemidnight-commands:
   - broadcast The daily restart is coming up in 1 minute!
   midnight-commands:
   - broadcast Server restart!
   - stop

# TabCompleteHider: Stops the server from returning all commands if a player types / and presses TAB
tabcompletehider:
   enabled: true

# TimedPermissions: Takes care of cross-server-restarts-timed-permissions
timedpermissions:
   enabled: true

   
   
   
   
   # DON'T CHANGE THIS !!!!!
# Is maintenance mode running? This can be changed with the command. DON'T CHANGE IT HERE
running: false
   
