name: UnknownUtilities
main: net.omniscimus.unknownutilities.UnknownUtilities
version: 1.4.0
description: This plugin provides some useful features for The Unknown.
author: Omniscimus
softdepend: [WorldEdit,WorldGuard,UniversalVotes,Vault,PermissionsEx]
commands:
   unknownutilities:
      description: Admin command for UnknownUtilities.
      usage: /unknownutilities help
      aliases: [uu]
   maintenance:
      description: Toggle Maintenance Mode.
      usage: /maintenance <on|off>
   wither:
      description: Fight the Wither!
      usage: /wither
   prefix:
      description: Change your level prefix!
      usage: /prefix <prefix>
   ubr:
      description: Send a plain broadcast.
      usage: /ubr <message>
   umsg:
      description: Send a plain message.
      usage: /umsg <player> <message>
   timedpermission:
      description: Give someone a timed permission.
      usage: /timedpermission <player> <permission>
